name: build gphoto2 macOS
on: workflow_dispatch

jobs:
  build:
    name: build on ${{ runner.os }} ${{ runner.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13, macos-14
        include:
          - os: macos-13
            target: "13.0"
          - os: macos-14
            target: "14.0"
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: jim-easterbrook/python-gphoto2
          ref: devel

      - name: Download libgphoto2
        run: wget -nv
          https://github.com/gphoto/libgphoto2/releases/download/v2.5.31/libgphoto2-2.5.31.tar.xz
          -O libgphoto2.tar.xz

      - name: Extract libgphoto2
        run: |
          mkdir $PWD/libgphoto2
          tar xf libgphoto2.tar.xz \
            --directory $PWD/libgphoto2 --strip-components=1

      - name: Install dependencies
        run: brew install libexif libtool gd

      - name: Build libgphoto2
        run: |
          cd $PWD/libgphoto2
          ./configure --prefix=$PWD/local_install --disable-internal-docs \
            --enable-vusb \
            CFLAGS="-D_DARWIN_C_SOURCE -I$(brew --prefix)/include"
          make
          make install

      - name: Build wheels
        # cibuildwheel@v3.x omits Python 3.6 & 3.7
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_ARCHS: auto64
          CIBW_BUILD: cp38*-macosx*
          CIBW_ENVIRONMENT: GPHOTO2_ROOT=$PWD/libgphoto2/local_install
          CIBW_ENVIRONMENT_MACOS: >
            MACOSX_DEPLOYMENT_TARGET=${{ matrix.target }}
            SYSTEM_VERSION_COMPAT=0
          CIBW_TEST_COMMAND: >
            python3 -m gphoto2 -v &&
            python3 -m unittest discover {project}/tests -v

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: gphoto2-wheels-${{ runner.os }}-${{ runner.arch }}
          path: wheelhouse/*.whl
