name: Test build libgphoto2 for Raspberry Pi
on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
        with:
          repository: jim-easterbrook/python-gphoto2

      - name: Check out Doxy2Swig
        uses: actions/checkout@v2
        with:
          repository: m7thon/doxy2swig
          path: doxy2swig

      - name: Download libgphoto2
        run: wget -nv https://github.com/gphoto/libgphoto2/releases/download/v2.5.27/libgphoto2-2.5.27.tar.xz

      - name: Extract libgphoto2
        run: tar xf libgphoto2-2.5.27.tar.xz

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.7'

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: arm/v6

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_ARCHS: arm
          CIBW_ENVIRONMENT: GPHOTO2_VERSION=2.5.27
          CIBW_BEFORE_ALL: >
            yum install -y libusb-devel libexif-devel libjpeg-turbo-devel \
              gd-devel doxygen &&
            cd libgphoto2-2.5.27 &&
            ./configure --prefix=$PWD/local_install --disable-internal-docs &&
            make &&
            make install &&
            cd .. &&
            python developer/build_doc.py 2.5.27 &&
            python developer/build_swig.py 2.5.27

      - name: Store results
        uses: actions/upload-artifact@v2
        with:
          name: manylinux-wheel
          path: wheelhouse/*.whl
