name: Build python-exiv2 wheels
on: workflow_dispatch

jobs:
  build:
    name: build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-13]
#        os: [ubuntu-22.04, ubuntu-22.04-arm, macos-13, macos-14]
#        include:
#          - os: macos-13
#            target: 13.0
#          - os: macos-14
#            target: 14.0
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: jim-easterbrook/python-exiv2
          ref: devel

      - name: Download exiv2
        env:
          SRC: >
            https://github.com/Exiv2/exiv2/archive/refs/tags/v0.28.5.tar.gz
        run: >
          mkdir libexiv2 &&
          wget -nv $SRC -O - |
          tar zxf - --directory libexiv2 --strip-components=1

      - name: Download inih
        if: ${{ runner.os == 'Linux' }}
        env:
          SRC: https://github.com/benhoyt/inih/archive/r58/inih-r58.tar.gz
        run: >
          mkdir inih &&
          wget -nv $SRC -O - |
          tar zxf - --directory inih --strip-components=1

      - name: Build libgphoto2
        if: ${{ runner.os == 'macOS' }}
        run: >
          brew install ninja inih &&
          cd libexiv2 &&
          cmake --preset base_mac
          -D EXIV2_BUILD_SAMPLES=OFF
          -D EXIV2_BUILD_UNIT_TESTS=OFF
          -D EXIV2_ENABLE_NLS=ON
          -D EXIV2_ENABLE_FILESYSTEM_ACCESS=ON
          -D EXIV2_BUILD_EXIV2_COMMAND=OFF
          -D EXIV2_TEAM_WARNINGS_AS_ERRORS=OFF &&
          cmake --build build-base_mac --config Release &&
          cmake --install build-base_mac --config Release

      - name: Build wheels
        # cibuildwheel@v3.x omits Python 3.6 & 3.7
        uses: pypa/cibuildwheel@v2.23.3
        env:
          CIBW_ARCHS: auto64
          CIBW_MANYLINUX_X86_64_IMAGE: manylinux_2_28
          CIBW_MANYLINUX_AARCH64_IMAGE: manylinux_2_28
          CIBW_ENVIRONMENT_LINUX: >
            EXIV2_ROOT=libexiv2/build-linux-release/install
          CIBW_ENVIRONMENT_MACOS: >
            EXIV2_ROOT=libexiv2/build-base_mac/install
            MACOSX_DEPLOYMENT_TARGET="10.15"
          CIBW_BUILD: "cp38*"
          CIBW_SKIP: "*musllinux*"
          CIBW_TEST_COMMAND: >
            python3 -m exiv2 -v &&
            python3 -m unittest discover {project}/tests -v
          CIBW_BEFORE_ALL_LINUX: >
            yum install -y --nogpgcheck zlib-devel expat-devel gettext-devel
            libcurl-devel brotli-devel meson &&
            localedef -c -i de_DE -f UTF-8 de_DE.UTF-8 &&
            pip install ninja &&
            cd inih && mkdir build && cd build &&
            meson setup --prefix=/usr --buildtype=release .. &&
            ninja && ninja install &&
            cd ../../libexiv2 &&
            cmake --preset linux-release
            -D CONAN_AUTO_INSTALL=OFF
            -D EXIV2_BUILD_SAMPLES=OFF
            -D EXIV2_BUILD_UNIT_TESTS=OFF
            -D EXIV2_ENABLE_NLS=ON
            -D EXIV2_ENABLE_FILESYSTEM_ACCESS=ON
            -D EXIV2_BUILD_EXIV2_COMMAND=OFF
            -D EXIV2_TEAM_WARNINGS_AS_ERRORS=OFF &&
            cmake --build build-linux-release --config Release &&
            cmake --install build-linux-release --config Release

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: exiv2-wheels-${{ runner.os }}-${{ runner.arch }}
          path: wheelhouse/*.whl
