name: Build Windows wheels exiv2 0.27
on: workflow_dispatch

jobs:
  compile:
    runs-on: windows-2019
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: jim-easterbrook/python-exiv2
          ref: v0.16

      - name: Fetch Exiv2 source
        run: >
          c:\msys64\usr\bin\wget.exe -nv
          https://github.com/Exiv2/exiv2/releases/download/v0.27.7/exiv2-0.27.7-Source.tar.gz
          -O exiv2.tar.gz

      - name: Extract Exiv2 source
        shell: bash
        run: |
          tar -xzf exiv2.tar.gz
          mv exiv2-0.27.7-Source libexiv2

      - name: Make directories
        run: |
          mkdir libexiv2/build-win32
          mkdir gettext

      - name: Fetch gettext
        run: >
          c:\msys64\usr\bin\wget.exe -nv
          https://github.com/mlocati/gettext-iconv-windows/releases/download/v0.21-v1.16/gettext0.21-iconv1.16-shared-64.zip
          -O gettext.zip

      - name: Install gettext
        working-directory: ./gettext
        shell: bash
        run: unzip ../gettext.zip

      - name: Install pip dependencies
        run: >
          pip install --disable-pip-version-check wheel conan==1.59.0

      - name: Install conan dependencies
        working-directory: ./libexiv2/build-win32
        run: >
          conan install .. -o unitTests=False -o iconv=True
          -o webready=True -b missing

      - name: Configure build
        working-directory: ./libexiv2
        run: >
          cmake -B build-win32 -DCMAKE_BUILD_TYPE=Release
          -D CMAKE_INSTALL_PREFIX=build-win32/install
          -D CMAKE_PREFIX_PATH=${{ github.workspace }}/gettext
          -D EXIV2_ENABLE_WIN_UNICODE=ON
          -D EXIV2_BUILD_SAMPLES=OFF
          -D EXIV2_BUILD_EXIV2_COMMAND=OFF
          -D EXIV2_ENABLE_BMFF=ON
          -D EXIV2_ENABLE_NLS=ON
          -D EXIV2_ENABLE_VIDEO=ON
          -D EXIV2_ENABLE_WEBREADY=ON
          -D CMAKE_CXX_STANDARD=98
          -G "Visual Studio 16 2019" -A x64

      - name: Do build
        working-directory: ./libexiv2
        run: |
          cmake --build build-win32 --config Release
          cmake --install build-win32 --config Release

      - name: Store intermediate files
        uses: actions/upload-artifact@v3
        with:
          name: exiv2-windows
          path: ./libexiv2/build-win32/install
          retention-days: 1

  wheels:
    needs: compile
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ['3.8']
#        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: jim-easterbrook/python-exiv2
          ref: v0.16

      - name: Fetch intermediate files
        uses: actions/download-artifact@v3
        with:
          name: exiv2-windows
          path: lib_exiv2

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Build wheel
        run: |
          pip3 install --disable-pip-version-check setuptools wheel
          pip wheel -v .
        env:
          EXIV2_ROOT: lib_exiv2

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: windows-wheel
          path: ./*.whl

  test:
    needs: wheels
    runs-on: windows-2019
    strategy:
      matrix:
        python-version: ['3.8']
#        python-version: ['3.6', '3.7', '3.8', '3.9', '3.10', '3.11', '3.12']
    steps:
      - name: Fetch wheel files
        uses: actions/download-artifact@v3
        with:
          name: windows-wheel

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
          architecture: 'x64'

      - name: Install wheel
        run: pip3 install --disable-pip-version-check --no-index --find-links=. exiv2

      - name: Check out repository code
        uses: actions/checkout@v4
        with:
          repository: jim-easterbrook/python-exiv2
          ref: v0.16

      - name: Get package details
        run: python3 -m exiv2 -v

      - name: Run unit tests
        run: python3 -m unittest discover tests -v
