name: Build MacOS binary wheels (ARM)
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: jim-easterbrook/python-gphoto2

      - name: Download libgphoto2
        run: wget -nv
          https://github.com/gphoto/libgphoto2/releases/download/v2.5.30/libgphoto2-2.5.30.tar.xz
          -O libgphoto2.tar.xz

      - name: Extract libgphoto2
        run: |
          mkdir $PWD/libgphoto2
          tar xf libgphoto2.tar.xz \
            --directory $PWD/libgphoto2 --strip-components=1

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3
        env:
          CIBW_ARCHS: arm64
          CIBW_SKIP: pp3?-*
          CIBW_ENVIRONMENT: GPHOTO2_ROOT=$PWD/libgphoto2/local_install
          CIBW_BEFORE_ALL: >
            brew install libexif jpeg-turbo libtool --universal &&
            pushd $PWD/libgphoto2 &&
            ./configure --prefix=$PWD/local_install --disable-internal-docs \
                --host=aarch64-apple-darwin \
                CFLAGS="-D_DARWIN_C_SOURCE -target arm64-apple-macos" &&
            make &&
            make install &&
            popd

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: macos-wheels
          path: wheelhouse/*.whl
