name: Build MacOS binary wheels (ARM)
on: workflow_dispatch

jobs:
  build:
    runs-on: macos-latest
    env:
      GPHOTO2_SRC: ${{ github.workspace }}/libgphoto2
    steps:
      - name: Check out repository code
        uses: actions/checkout@v3
        with:
          repository: jim-easterbrook/python-gphoto2

      - name: Download libgphoto2
        run: |
          wget -nv \
            https://github.com/gphoto/libgphoto2/releases/download/v2.5.30/libgphoto2-2.5.30.tar.xz \
            -O libgphoto2.tar.xz
          mkdir $GPHOTO2_SRC
          tar xf libgphoto2.tar.xz \
            --directory $GPHOTO2_SRC --strip-components=1

      - name: Build libgphoto2
        working-directory: ${{ env.GPHOTO2_SRC }}
        run: |
          PACKAGES=(libexif libtool)
          for PACKAGE in "${PACKAGES[@]}"
          do
            brew uninstall --force --ignore-dependencies $PACKAGE
            brew fetch --force --bottle-tag=arm64_monterey $PACKAGE
            brew install $(brew --cache --bottle-tag=arm64_monterey $PACKAGE)
          done
          ./configure --prefix=$PWD/local_install --disable-internal-docs \
              --host=aarch64-apple-darwin \
              CFLAGS="-D_DARWIN_C_SOURCE -arch arm64 -target arm64-apple-macos"
          make
          make install

      - name: Build wheels
        uses: pypa/cibuildwheel@v2.12.3
        env:
          CIBW_ARCHS: arm64
          CIBW_SKIP: pp3?-*
          CIBW_ENVIRONMENT: GPHOTO2_ROOT=${{ env.GPHOTO2_SRC }}/local_install

      - name: Store results
        uses: actions/upload-artifact@v3
        with:
          name: macos-wheels
          path: wheelhouse/*.whl
