name: Photini MacOS install
on: workflow_dispatch

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: Install
        run: pip3 install PySide2 python-exiv2 appdirs requests photini

      - name: Test
        run: python3 -m photini.editor -t -v --version
