name: Photini MacOS install
on: workflow_dispatch

jobs:
  test:
    runs-on: macos-10.15
    steps:
      - name: Install
        run: |
          brew install enchant
          pip3 install PySide2 python-exiv2 photini pyenchant gpxpy

      - name: Test
        run: python3 -m photini.editor -t -v --version
